### ISSUE TITLE
Issues Voice Recorder 

### ISSUE THREAD

**Issue by FarshidRoohi** [FarshidRoohi/ReminderPro#9]

**Comment by FarshidRoohi** [comment]
`
2021-03-05 20:51:31.774 5796-5796/ir.farshid.roohi.reminderpro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.farshid.roohi.reminderpro, PID: 5796
    java.lang.RuntimeException: setAudioSource failed.
        at android.media.MediaRecorder.setAudioSource(Native Method)
        at ir.roohi.farshid.reminderpro.utility.ExtensionKt.initialize(Extension.kt:116)
        at ir.roohi.farshid.reminderpro.views.activities.VoiceRecordActivity$onCreate$3.onClick(VoiceRecordActivity.kt:58)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

**Comment by FarshidRoohi** [comment]
Bug fix pr #19
